# datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/nsj?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#mrybatis.mappe-locations=classpath:mappers/*.xml
#server.port=8022
#
#fileUploadPath = D:

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/localdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8022

mybatis:
  mapperLocations: classpath:mappers/*.xml
# linux下
#file:
#  upload:
#    path: /usr/local/project-file

# win下
file:
  upload:
    path: D:/ProjectFile

